### ISSUE TITLE
Lost syntax color highlighting when setting filetype for jinja2?

### ISSUE THREAD

**Issue by quantonganh** [saltstack/salt-vim#14]
By default, `filetype` is off for `*.jinja2`. To make the [UltiSnips](https://github.com/SirVer/ultisnips) work, I have to turn on the filetype:

```
:se ft=jinja2
```

but syntax highlighting disappeared after that.

How can I turn on the filetype for jjinja2 without losing the syntax highlighting?

**Comment by gravyboat** [comment]
@quantonganh Can we close this issue?
