### ISSUE TITLE
Evil Mode

### ISSUE THREAD

**Issue by v6** [saltstack/salt-vim#29]
Please mention evil-mode compatibility in the readme? 

I'm an eviller, myself. I just love lisp too much. 

In every other respect's vim's superior, and evil suits.

**Comment by gravyboat** [comment]
@v6 Can you please elaborate on what you'd like to see? Or better yet, make a PR to add the relevant information you would like to see?

**Comment by v6** [comment]
// , I like your avatar! 

I could certainly make a PR. I usually don't like to make one without sending an issue, first. 

I'm looking for a way to use these with Emacs. Evil-mode is a way to use Vim, but as a mode for Emacs. It's the successor to Vimpulse and vim-mode. This means that it works by means of LISP, and allows, to me, the best of both worlds. 

However, I have done some clever searches, but I haven't found a way to use .vim files in Emacs Evil-mode. 

This might be a better question for stackexchange, or something, but I guess if there's an obvious way to use .vim files like these with Evil-Mode, I would try it out. 

P.S. @gravyboat, I like the dog avatar.

**Comment by gravyboat** [comment]
@v6 Ahh I see, as far as I know vim files don't work with evil mode, but I am not extremely familiar with emacs so I could be full of it! Unfortunately there isn't a salt-emacs repo, but I did see this: https://stackoverflow.com/questions/27737557/saltstack-mode-for-emacs If you're familiar enough with emacs to where you can write the plugin we can talk to the devs about creating that repo. Thanks for your compliment regarding the avatar, it's Jake from Adventure Time!
