### ISSUE TITLE
Dog-slow in sls with long lines

### ISSUE THREAD

**Issue by kremso** [saltstack/salt-vim#32]
When there are long lines in the sls, whole vim becomes very unresponsive and slow. I have an sls where multiple ssh public keys are listed and the only way I can edit that is by setting `set ft=none`.

**Comment by kremso** [comment]
Oh, I just found https://github.com/saltstack/salt-vim/issues/20

Apparently, switching back to the old regexp engine is not a real fix. I did try an alternative yaml highlighter though and that  fixed it. Would you accept a simple PR where I describe the problem and outline the fix in the readme?

**Comment by gravyboat** [comment]
@kremso I don't see why there would be opposition to that! Sorry for the delay on responding to this, please make the PR that outlines the fix!

**Comment by kremso** [comment]
@gravyboat Added the PR. Thanks!

**Comment by ndewing** [comment]
@kremso Thanks for fix! Could we close this issue?

**Comment by kremso** [comment]
Yes!
