### ISSUE TITLE
Fold/unfold all?

### ISSUE THREAD

**Issue by justindowning** [saltstack/salt-vim#34]
Is it possible to toggle fold/unfold all sections of a state file with one command? Scrolling to each fold and pressing 'space' on many folds is time consuming. TIA!

**Comment by cro** [comment]
Does

zR

work?

On Fri, May 22, 2015 at 8:22 AM, Justin Downing <notifications@github.com>
wrote:

> Is it possible to toggle fold/unfold all sections of a state file with one
> command? Scrolling to each fold and pressing 'space' on many folds is time
> consuming. TIA!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt-vim/issues/34>.
>



-- 
*--cro*
C. R. Oldham, Platform Engineer, SaltStack
cr@saltstack.com / 801-564-4673

**Comment by justindowning** [comment]
@cro YESSS! Thank you! :blue_heart: 

Is that a vim thing I should have known or part of the plugin?

**Comment by cro** [comment]
It's a Vim thing for all Vim folding modes I think.

On Fri, May 22, 2015 at 9:40 AM, Justin Downing <notifications@github.com>
wrote:

> @cro <https://github.com/cro> YESSS! Thank you! [image: :blue_heart:]
>
> Is that a vim thing I should have known or part of the plugin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt-vim/issues/34#issuecomment-104694322>.
>



-- 
*--cro*
C. R. Oldham, Platform Engineer, SaltStack
cr@saltstack.com / 801-564-4673

**Comment by justindowning** [comment]
@cro Cool -- thanks again.

**Comment by ndewing** [comment]
@justindowning Checkout http://vim.wikia.com/wiki/Folding for other hot keys related working with folds.
